### PR TITLE
Update station2.py

### PR DESCRIPTION
**Pull request by rr0r4r**

### CODE REVIEW

**Comment by ArshTumo** [comment]
In case you have a goal number and  you roll a 7, you lose the game. But in your game you win.

**Comment by AnnaHambardzumyan** [comment]
I think you misunderstood the game.  After rolling the dice for the first time your goal becomes that number if you haven't already won(rolling 7 or 11) or lose(rolling 2, 3 or 12) and you need to roll that number to win. But if you roll a 7,  you lose.

**Comment by rr0r4r** [comment]
@ArshTumo @AnnaHambardzumyan I changed the code issues, can u check it one more time?

**Comment by rr0r4r** [comment]
@AnnaHambardzumyan @ArshTumo I changed the code issues, can u check it one more time?

**Comment by ArshTumo** [comment]
Yeah, that worked correctly

**Comment by AnnaHambardzumyan** [comment]
Now it's okay and works as it should.

**Pull request merged**
